use super::entity::CanyonEntity;
use crate::helpers;
use proc_macro2::{Ident, Span, TokenStream};
use quote::quote;
use syn::{Attribute, Generics, Visibility};

/// Builds the TokenStream that contains the user defined struct
pub fn generate_user_struct(canyon_entity: &CanyonEntity) -> TokenStream {
    let fields = &canyon_entity.get_attrs_as_token_stream();

    let struct_name: &Ident = &canyon_entity.struct_name;
    let struct_visibility: &Visibility = &canyon_entity.vis;
    let struct_generics: &Generics = &canyon_entity.generics;
    let struct_attrs: &Vec<Attribute> = &canyon_entity.attrs;

    quote! {
        #(#struct_attrs)*
        #struct_visibility struct #struct_name #struct_generics {
            #(#fields),*
        }
    }
}

pub fn generated_enum_type_for_struct_data(canyon_entity: &CanyonEntity) -> TokenStream {
    let struct_name = canyon_entity.struct_name.to_string();
    let enum_name = Ident::new(&(String::from(&struct_name) + "Table"), Span::call_site());
    let db_target_table_name = helpers::default_database_table_name_from_entity_name(&struct_name);

    let generics = &canyon_entity.generics;
    let visibility = &canyon_entity.vis;

    quote! {
        /// Auto-generated enum to represent compile-time metadata
        /// about a Canyon entity type.
        ///
        /// The enum is named by appending `Table` to the struct name and contains
        /// variants for retrieving metadata associated with the entity. Currently,
        /// it includes:
        ///
        /// - `name`: The struct's identifier as a string.
        /// - `DbName`: The name of the database table derived from the struct's name,
        ///                    but adapted to the `snake_case` convention, which is the standard adopted
        ///                    by Canyon these early days to transform type Idents into table names
        ///
        /// This enum implements the `TableMetadata` trait, providing the `as_str` method,
        /// which is useful in code that needs to retrieve such metadata dynamically while
        /// keeping strong typing and avoiding magic strings.
        ///
        /// # Example
        /// ```
        /// pub struct League {
        ///     id: i32,
        ///     name: String,
        /// }
        ///
        /// // This is the auto-generated by Canyon with the `Fields` macro
        /// pub enum LeagueTable {
        ///     Name,
        ///     DbName
        /// }
        ///
        /// assert_eq!(LeagueTable::Name.to_string(), "League");
        /// assert_eq!(LeagueTable::DbName.to_string(), "league");
        /// ```
        #visibility enum #enum_name #generics  {
            Name,
            DbName
        }

        impl #generics std::fmt::Display for #enum_name #generics {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "{}", self.as_str())
            }
        }

        impl #generics canyon_sql::query::bounds::TableMetadata<'_> for #generics #enum_name #generics {
            fn as_str(&self) -> &'static str {
                match *self {
                    #enum_name::Name => #struct_name,
                    #enum_name::DbName => #db_target_table_name,
                }
            }
        }
    }
}

/// Auto-generated enum to represent every field of the related type
/// as a variant of an enum that it's named with the concatenation
/// of the type identifier + Field
///
/// The idea it's to have a representation of the field name as an enum
/// variant, letting the user passing around Strings and instead,
/// passing variants of a concrete enumeration type, that when required,
/// will be called though macro code to obtain the &str representation
/// of the field name.
pub fn generate_enum_with_fields(canyon_entity: &CanyonEntity) -> TokenStream {
    let struct_name = canyon_entity.struct_name.to_string();
    let db_target_table_name = helpers::default_database_table_name_from_entity_name(&struct_name);

    let enum_name = Ident::new((struct_name + "Field").as_str(), Span::call_site());

    let fields_names = &canyon_entity.get_fields_as_enum_variants();
    let match_arms_str = &canyon_entity.create_match_arm_for_get_variant_as_str(&enum_name);

    let visibility = &canyon_entity.vis;
    let generics = &canyon_entity.generics;

    quote! {
        #[allow(non_camel_case_types)]
        #[allow(unused_variables)]
        #[allow(dead_code)]
        /// Auto-generated enum to represent every field of the related type
        /// as a variant of an enum that it's named with the concatenation
        /// of the type identifier + Field
        ///
        /// The idea it's to have a representation of the field name as an enum
        /// variant, avoiding the user to have to pass around Strings and instead,
        /// passing variants of a concrete enumeration type, that when required,
        /// will be called though macro code to obtain the &str representation
        /// of the field name.
        ///
        /// That's particularly useful in Canyon when working with queries being constructed
        /// through the [`QueryBuilder`], when one of the methods requires to get
        /// a column name (which is the name of some field of the type) as a parameter
        ///
        /// ```
        /// pub struct League {
        ///     id: i32,
        ///     name: String
        /// }
        ///
        /// #[derive(Debug)]
        /// #[allow(non_camel_case_types)]
        /// pub enum LeagueField {
        ///     id(i32),
        ///     name(String)
        /// }
        /// ```
        #visibility enum #enum_name #generics {
            #(#fields_names),*
        }

        impl #generics std::fmt::Display for #enum_name #generics {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "{}", self.as_str())
            }
        }

        impl #generics canyon_sql::query::bounds::FieldIdentifier for #generics #enum_name #generics {
            #[inline(always)]
            fn table_and_column_name(&self) -> String {
                format!("{}.{}", #db_target_table_name, self.as_str())
            }

            fn as_str(&self) -> &'static str {
                match *self {
                    #(#match_arms_str),*
                }
            }
        }
    }
}

/// Autogenerated Rust Enum type that contains as many variants
/// with inner value as fields has the structure to which it relates
///
/// The type of the inner value `(Enum::Variant(SomeType))` is the same
/// that the field that the variant represents
pub fn generate_enum_with_fields_values(canyon_entity: &CanyonEntity) -> TokenStream {
    let struct_name = canyon_entity.struct_name.to_string();
    let enum_name = Ident::new((struct_name + "FieldValue").as_str(), Span::call_site());

    let fields_names = &canyon_entity.get_fields_as_enum_variants_with_value();
    let match_arms = &canyon_entity.create_match_arm_for_relate_fields_with_values(&enum_name);

    let visibility = &canyon_entity.vis;

    quote! {
        #[allow(non_camel_case_types)]
        #[allow(unused_variables)]
        #[allow(dead_code)]
        /// Auto-generated enumeration to represent each field of the related
        /// type as a variant, which can support and contain a value of the field data type.
        ///
        /// ```
        /// pub struct League {
        ///     id: i32,
        ///     name: String,
        ///     opt: Option<String>
        /// }
        ///
        /// #[derive(Debug)]
        /// #[allow(non_camel_case_types)]
        /// pub enum LeagueFieldValue {
        ///     id(i32),
        ///     name(String),
        ///     opt(Option<String>)
        /// }
        /// ```
        #visibility enum #enum_name {
            #(#fields_names),*
        }

        impl canyon_sql::query::bounds::FieldValueIdentifier for #enum_name {
            fn value(&self) -> (&'static str, &dyn canyon_sql::query::QueryParameter) {
                match self {
                    #(#match_arms),*
                }
            }
        }
    }
}
