use crate::utils::macro_tokens::MacroTokens;
use canyon_entities::field_annotation::EntityFieldAnnotation;
use canyon_entities::helpers::database_table_name_to_struct_ident;
use proc_macro2::{Ident, TokenStream};
use quote::{format_ident, quote};

/// Generates all read operations derived from Canyon's `foreign_key` field annotation.
///
/// A foreign key represents an outbound relationship from the current entity to another
/// entity. For example, if `Player.team_id` points to `Team.id`, then `Player` owns the
/// foreign-key column and `Team` is the referenced parent entity.
///
/// From a single `foreign_key(table = "teams", column = "id")` annotation, Canyon generates
/// two families of operations:
///
/// - Parent lookup operations: instance methods that start from the child entity and fetch
///   the referenced parent entity. Example: `player.search_teams().await`.
/// - Child lookup operations: associated functions that start from a parent entity and fetch
///   all child rows that reference it. Example: `Player::search_teams_childrens(&team).await`.
///
/// The generated method names are kept for backwards compatibility. Internally, the code uses
/// the terms `parent_lookup` and `child_lookup` because they map directly to the direction of
/// the database relationship.
pub fn generate_find_by_fk_ops(
    macro_data: &MacroTokens<'_>,
    table_schema_data: &str,
) -> TokenStream {
    __operations::generate_find_by_fk_ops(macro_data, table_schema_data)
}

mod __operations {
    use super::*;
    use crate::utils::helpers::{CanyonMethodKind, ReturnTypeTokens};

    pub(super) fn generate_find_by_fk_ops(
        macro_data: &MacroTokens<'_>,
        table_schema_data: &str,
    ) -> TokenStream {
        let ty = &macro_data.ty;
        let fk_trait_ident = fk_operations_trait_ident(ty);

        let parent_lookup_operations = generate_parent_lookup_tokens(macro_data);
        let child_lookup_operations = generate_child_lookup_tokens(macro_data, table_schema_data);

        if parent_lookup_operations.is_empty() && child_lookup_operations.is_empty() {
            return TokenStream::new();
        }

        let method_signatures = parent_lookup_operations
            .iter()
            .chain(child_lookup_operations.iter())
            .map(FkOperationTokens::signature);

        let method_implementations = parent_lookup_operations
            .iter()
            .chain(child_lookup_operations.iter())
            .map(FkOperationTokens::implementation);

        quote! {
            /// Hidden trait that exposes the foreign-key read operations generated by Canyon.
            ///
            /// The concrete method names depend on each `foreign_key` annotation, so they cannot
            /// be declared statically in `CrudOperations`.
            pub trait #fk_trait_ident<#ty> {
                #(#method_signatures)*
            }

            impl #fk_trait_ident<#ty> for #ty
            where
                #ty: std::fmt::Debug + canyon_sql::core::RowMapper,
            {
                #(#method_implementations)*
            }
        }
    }

    fn fk_operations_trait_ident(ty: &Ident) -> Ident {
        format_ident!("{}FkOperations", ty)
    }

    /// Generates parent lookup operations for every foreign-key field declared by the entity.
    ///
    /// A parent lookup follows the foreign-key reference from the current row to the row it points
    /// to. In relational terms, this is the many-to-one side of the relationship.
    fn generate_parent_lookup_tokens(macro_data: &MacroTokens<'_>) -> Vec<FkOperationTokens> {
        macro_data
            .get_fk_annotations()
            .iter()
            .filter_map(|(field_ident, annotation)| match annotation {
                EntityFieldAnnotation::ForeignKey(table, column) => Some((field_ident, table, column)),
                _ => None,
            })
            .flat_map(|(field_ident, table, column)| {
                let parent_ty = database_table_name_to_struct_ident(table);
                // TODO: we must ensure that the generated method names are singular, so there's no confusion with the child lookup methods.
                let method_name = format_ident!("search_{}", table);
                let method_name_with = format_ident!("search_{}_with", table);
                let query_source = __detail::LookupQuerySource::Parent {
                    table,
                    predicate_column: column,
                };

                let fk_operation = __impl::generate_fk_operations_tokens(
                    query_source,
                    field_ident,
                    &method_name,
                    &parent_ty,
                    ReturnTypeTokens::Option,
                    CanyonMethodKind::Default,
                );

                let fk_operation_with = __impl::generate_fk_operations_tokens(
                    query_source,
                    field_ident,
                    &method_name_with,
                    &parent_ty,
                    ReturnTypeTokens::Option,
                    CanyonMethodKind::WithInput,
                );

                [fk_operation, fk_operation_with]
            })
            .collect()
    }

    /// Generates child lookup operations for every foreign-key field declared by the entity.
    ///
    /// This is sometimes called a "reverse foreign-key search", but the database does not contain
    /// a second or inverted foreign key. The same child table foreign-key column is reused in the
    /// opposite navigation direction: starting from a parent row, Canyon fetches all child rows that
    /// reference it.
    fn generate_child_lookup_tokens(
        macro_data: &MacroTokens<'_>,
        table_schema_data: &str,
    ) -> Vec<FkOperationTokens> {
        let ty = macro_data.ty;
        let mapper_ty = macro_data
            .retrieve_mapping_target_type()
            .as_ref()
            .unwrap_or(ty);

        macro_data
            .get_fk_annotations()
            .iter()
            .filter_map(|(field_ident, annotation)| match annotation {
                EntityFieldAnnotation::ForeignKey(table, column) => Some((field_ident, table, column)),
                _ => None,
            })
            .flat_map(|(field_ident, table, column)| {
                let method_name = format_ident!("search_{}_childrens", table);
                let method_name_with = format_ident!("search_{}_childrens_with", table);
                let field_name = field_ident.to_string();
                let lookup_value = lookup_value(column, table);
                let query_source = __detail::LookupQuerySource::Child {
                    table: table_schema_data,
                    predicate_column: &field_name,
                };

                let child_operation = __impl::generate_child_fk_operations_tokens(
                    query_source,
                    &lookup_value,
                    &method_name,
                    mapper_ty,
                    CanyonMethodKind::Default,
                );

                let child_operation_with = __impl::generate_child_fk_operations_tokens(
                    query_source,
                    &lookup_value,
                    &method_name_with,
                    mapper_ty,
                    CanyonMethodKind::WithInput,
                );

                [child_operation, child_operation_with]
            })
            .collect()
    }

    /// Generates the expression that extracts the referenced parent column value from a
    /// `ForeignKeyable` parent entity.
    fn lookup_value(column: &str, table: &str) -> TokenStream {
        let column = column.to_owned();
        let table = table.to_owned();

        quote! {
            value.get_fk_column(#column)
                .ok_or_else(|| format!(
                    "Column: {:?} not found in type: {:?}",
                    #column,
                    #table,
                ))?
        }
    }
}

mod __impl {
    use super::*;
    use crate::utils::helpers::{CanyonMethodKind, ReturnTypeTokens};

    pub(crate) fn generate_fk_operations_tokens(
        query_source: __detail::LookupQuerySource<'_>,
        field_ident: &Ident,
        method_name: &Ident,
        parent_ty: &Ident,
        return_type_tokens: ReturnTypeTokens,
        method_kind: CanyonMethodKind,
    ) -> FkOperationTokens {
        __detail::generate_operation_tokens(
            query_source,
            __detail::LookupValueSource::SelfField(field_ident),
            method_name,
            parent_ty,
            return_type_tokens,
            __detail::FkLookupKind::Parent,
            method_kind,
        )
    }

    pub(crate) fn generate_child_fk_operations_tokens(
        query_source: __detail::LookupQuerySource<'_>,
        lookup_value: &TokenStream,
        method_name: &Ident,
        mapper_ty: &Ident,
        method_kind: CanyonMethodKind,
    ) -> FkOperationTokens {
        __detail::generate_operation_tokens(
            query_source,
            __detail::LookupValueSource::ForeignKeyable(lookup_value),
            method_name,
            mapper_ty,
            ReturnTypeTokens::Vec,
            __detail::FkLookupKind::Child,
            method_kind,
        )
    }
}

mod __detail {
    use super::*;
    use crate::utils::helpers::{CanyonMethodKind, ReturnTypeTokens};

    #[derive(Clone, Copy)]
    pub(super) enum FkLookupKind {
        Parent,
        Child,
    }

    #[derive(Clone, Copy)]
    pub(super) enum LookupQuerySource<'a> {
        Parent {
            table: &'a str,
            predicate_column: &'a str,
        },
        Child {
            table: &'a str,
            predicate_column: &'a str,
        },
    }

    #[derive(Clone, Copy)]
    pub(super) enum LookupValueSource<'a> {
        SelfField(&'a Ident),
        ForeignKeyable(&'a TokenStream),
    }

    pub(super) fn generate_operation_tokens(
        query_source: LookupQuerySource<'_>,
        lookup_value_source: LookupValueSource<'_>,
        method_name: &Ident,
        return_ty: &Ident,
        return_type_tokens: ReturnTypeTokens,
        lookup_kind: FkLookupKind,
        method_kind: CanyonMethodKind,
    ) -> FkOperationTokens {
        let signature = create_method_signature(
            method_name,
            return_ty,
            return_type_tokens,
            lookup_kind,
            method_kind,
        );

        let implementation = generate_method_implementation_body(
            query_source,
            lookup_value_source,
            return_ty,
            lookup_kind,
            method_kind,
        );

        FkOperationTokens::new(signature, implementation)
    }

    fn create_method_signature(
        method_name: &Ident,
        return_ty: &Ident,
        ret_ty: ReturnTypeTokens,
        lookup_kind: FkLookupKind,
        method_kind: CanyonMethodKind,
    ) -> TokenStream {
        let method_generics_and_args = method_generics_and_args(lookup_kind, method_kind);
        let where_clause = get_where_clause(lookup_kind, method_kind);

        quote! {
            async fn #method_name #method_generics_and_args
                -> Result<#ret_ty<#return_ty>, Box<dyn std::error::Error + Send + Sync + 'a>>
                #where_clause
        }
    }

    fn method_generics_and_args(
        lookup_kind: FkLookupKind,
        method_kind: CanyonMethodKind,
    ) -> TokenStream {
        match (lookup_kind, method_kind) {
            (FkLookupKind::Parent, CanyonMethodKind::Default) => quote! { <'a>(&self) },
            (FkLookupKind::Parent, CanyonMethodKind::WithInput) => quote! { <'a, I>(&self, input: I) },
            (FkLookupKind::Child, CanyonMethodKind::Default) => quote! { <'a, F>(value: &F) },
            (FkLookupKind::Child, CanyonMethodKind::WithInput) => quote! { <'a, F, I>(value: &F, input: I) },
        }
    }

    fn get_where_clause(
        lookup_kind: FkLookupKind,
        method_kind: CanyonMethodKind,
    ) -> TokenStream {
        match (lookup_kind, method_kind) {
            (FkLookupKind::Parent, CanyonMethodKind::Default) => quote! {},
            (FkLookupKind::Parent, CanyonMethodKind::WithInput) => quote! {
                where I: canyon_sql::connection::DbConnection + Send + 'a
            },
            (FkLookupKind::Child, CanyonMethodKind::Default) => quote! {
                where F: canyon_sql::query::bounds::ForeignKeyable<F> + Send + Sync
            },
            (FkLookupKind::Child, CanyonMethodKind::WithInput) => quote! {
                where
                    F: canyon_sql::query::bounds::ForeignKeyable<F> + Send + Sync,
                    I: canyon_sql::connection::DbConnection + Send + 'a
            },
        }
    }

    fn connection_binding(method_kind: CanyonMethodKind) -> TokenStream {
        match method_kind {
            CanyonMethodKind::Default => quote! {
                let db_conn = canyon_sql::core::Canyon::instance()?
                    .get_default_connection()?;
            },
            CanyonMethodKind::WithInput => quote! {
                let db_conn = input;
            },
        }
    }

    fn query_builder_stmt(query_source: LookupQuerySource) -> TokenStream {
        let (table, predicate_column) = match query_source {
            LookupQuerySource::Parent { table, predicate_column } => (table, predicate_column),
            LookupQuerySource::Child { table, predicate_column } => (table, predicate_column),
        };

        quote! {
            let db_type = db_conn.get_database_type()?;
            let stmt = canyon_sql::query::querybuilder::SelectQueryBuilder::new(#table, db_type)
                .r#where(#predicate_column, canyon_sql::query::operators::Operator::Eq)
                .build()?;
        }
    }

    fn lookup_value_tokens(lookup_value_source: LookupValueSource<'_>) -> TokenStream {
        match lookup_value_source {
            LookupValueSource::SelfField(field_ident) => quote! {
                &self.#field_ident as &dyn canyon_sql::query::QueryParameter
            },
            LookupValueSource::ForeignKeyable(_) => quote! {
                lookup_value
            },
        }
    }

    fn lookup_value_binding(lookup_value_source: LookupValueSource<'_>) -> TokenStream {
        match lookup_value_source {
            LookupValueSource::SelfField(_) => quote! {},
            LookupValueSource::ForeignKeyable(lookup_value) => quote! {
                let lookup_value = #lookup_value;
            },
        }
    }

    fn query_execution_tokens(
        lookup_value_source: LookupValueSource<'_>,
        return_ty: &Ident,
        lookup_kind: FkLookupKind,
    ) -> TokenStream {
        let lookup_value = lookup_value_tokens(lookup_value_source);

        match lookup_kind {
            FkLookupKind::Parent => quote! {
                db_conn
                    .query_one::<#return_ty>(
                        stmt.sql(),
                        &[#lookup_value],
                    )
                    .await
            },
            FkLookupKind::Child => quote! {
                db_conn
                    .query::<&str, #return_ty>(
                        stmt.sql(),
                        &[#lookup_value],
                    )
                    .await
            },
        }
    }

    fn generate_method_implementation_body(
        query_source: LookupQuerySource<'_>,
        lookup_value_source: LookupValueSource<'_>,
        return_ty: &Ident,
        lookup_kind: FkLookupKind,
        method_kind: CanyonMethodKind,
    ) -> TokenStream {
        let connection_binding = connection_binding(method_kind);
        let lookup_value_binding = lookup_value_binding(lookup_value_source);
        let query_builder_stmt = query_builder_stmt(query_source);
        let query_execution = query_execution_tokens(lookup_value_source, return_ty, lookup_kind);

        quote! {
            {
                use crate::canyon_sql::query::querybuilder::{QueryBuilderOps, SelectQueryBuilderOps};

                #lookup_value_binding
                #connection_binding
                #query_builder_stmt
                #query_execution
            }
        }
    }
}


#[derive(Debug)]
struct FkOperationTokens {
    signature: TokenStream,
    implementation: TokenStream,
}

impl FkOperationTokens {
    fn new(signature: TokenStream, implementation: TokenStream) -> Self {
        let method_definition = quote! {
            #signature;
        };
        let method_implementation = quote! {
            #signature #implementation
        };
        Self {
            signature: method_definition,
            implementation: method_implementation,
        }
    }

    fn signature(&self) -> &TokenStream {
        &self.signature
    }

    fn implementation(&self) -> &TokenStream {
        &self.implementation
    }
}
