use crate::utils::helpers::database_table_name_to_struct_ident;
use crate::utils::macro_tokens::MacroTokens;
use canyon_entities::field_annotation::EntityFieldAnnotation;
use proc_macro2::{Ident, TokenStream};
use quote::quote;

pub fn generate_find_by_fk_ops(
    macro_data: &MacroTokens<'_>,
    table_schema_data: &str,
) -> TokenStream {
    let ty = &macro_data.ty;

    // Search by foreign (d) key as Vec, cause Canyon supports multiple fields having FK annotation
    let _search_by_fk_tokens: Vec<(TokenStream, TokenStream)> =
        generate_find_by_foreign_key_tokens(macro_data);
    let fk_method_signatures = _search_by_fk_tokens.iter().map(|(sign, _)| sign);
    let fk_method_implementations = _search_by_fk_tokens.iter().map(|(_, m_impl)| m_impl);

    // The tokens for generating the methods that enable Canyon to retrieve the child entities that are of T type
    // given a parent entity U: ForeignKeyable, as an associated function for the child type (T)
    let search_by_reverse_fk_tokens: Vec<(TokenStream, TokenStream)> =
        generate_find_by_reverse_foreign_key_tokens(macro_data, table_schema_data);
    let rev_fk_method_signatures = search_by_reverse_fk_tokens.iter().map(|(sign, _)| sign);
    let rev_fk_method_implementations =
        search_by_reverse_fk_tokens.iter().map(|(_, m_impl)| m_impl);

    // The autogenerated name for the trait that holds the fk and rev fk searches
    let fk_trait_ident = Ident::new(
        &format!("{}FkOperations", &ty.to_string()),
        proc_macro2::Span::call_site(),
    );

    if search_by_reverse_fk_tokens.is_empty() {
        return quote! {}; // early guard
    }

    quote! {
        /// Hidden trait for generate the foreign key operations available
        /// in Canyon without have to define them beforehand in CrudOperations
        /// because it's just impossible with the actual system (where the methods
        /// are generated dynamically based on some properties of the `foreign_key`
        /// annotation)
        pub trait #fk_trait_ident<#ty> {
            #(#fk_method_signatures)*
            #(#rev_fk_method_signatures)*
        }
        impl #fk_trait_ident<#ty> for #ty
        where #ty:
            std::fmt::Debug +
            canyon_sql::crud::CrudOperations<#ty> +
            canyon_sql::core::RowMapper<#ty>
            {
                #(#fk_method_implementations)*
                #(#rev_fk_method_implementations)*
            }
    }
}

/// Generates the TokenStream for build the search by foreign key feature, also as a method instance
/// of a T type of as an associated function of same T type, but wrapped as a Result<T, Err>, representing
/// a possible failure querying the database, a bad or missing FK annotation or a missed ForeignKeyable
/// derive macro on the parent side of the relation
fn generate_find_by_foreign_key_tokens(
    macro_data: &MacroTokens<'_>,
) -> Vec<(TokenStream, TokenStream)> {
    let mut fk_quotes: Vec<(TokenStream, TokenStream)> = Vec::new();

    for (field_ident, fk_annot) in macro_data.get_fk_annotations().iter() {
        if let EntityFieldAnnotation::ForeignKey(table, column) = fk_annot {
            let method_name = "search_".to_owned() + table;

            // TODO this is not a good implementation. We must try to capture the
            // related entity in some way, and compare it with something else
            let fk_ty = database_table_name_to_struct_ident(table);

            // Generate and identifier for the method based on the convention of "search_related_types"
            // where types is a placeholder for the plural name of the type referenced
            let method_name_ident = Ident::new(&method_name, proc_macro2::Span::call_site());
            let method_name_ident_with = Ident::new(
                &format!("{}_with", &method_name),
                proc_macro2::Span::call_site(),
            );
            let quoted_method_signature: TokenStream = quote! {
                async fn #method_name_ident<'a>(&self) ->
                    Result<Option<#fk_ty>, Box<(dyn std::error::Error + Sync + Send + 'a)>>
            };
            let quoted_with_method_signature: TokenStream = quote! {
                async fn #method_name_ident_with<'a, I>(&self, input: I) ->
                    Result<Option<#fk_ty>, Box<(dyn std::error::Error + Sync + Send + 'a)>>
                where I: canyon_sql::core::DbConnection + Send + 'a
            };

            let stmt = format!(
                "SELECT * FROM {} WHERE {} = $1",
                table,
                format!("\"{column}\"").as_str(),
            );
            fk_quotes.push((
                quote! { #quoted_method_signature; },
                quote! {
                    /// Searches the parent entity (if exists) for this type
                    #quoted_method_signature {
                        <#fk_ty as canyon_sql::core::Transaction<#fk_ty>>::query_one(
                            #stmt,
                            &[&self.#field_ident as &dyn canyon_sql::core::QueryParameter<'_>],
                            ""
                        ).await
                    }
                },
            ));

            fk_quotes.push((
                quote! { #quoted_with_method_signature; },
                quote! {
                    /// Searches the parent entity (if exists) for this type with the specified datasource
                    #quoted_with_method_signature {
                        <#fk_ty as canyon_sql::core::Transaction<#fk_ty>>::query_one(
                            #stmt,
                            &[&self.#field_ident as &dyn canyon_sql::core::QueryParameter<'_>],
                            input
                        ).await
                    }
                },
            ));
        }
    }

    fk_quotes
}

/// Generates the TokenStream for build the __search_by_foreign_key() CRUD
/// associated function, but wrapped as a Result<T, Err>, representing
/// a possible failure querying the database, a bad or missing FK annotation or a missed ForeignKeyable
/// derive macro on the parent side of the relation
fn generate_find_by_reverse_foreign_key_tokens(
    macro_data: &MacroTokens<'_>,
    table_schema_data: &str,
) -> Vec<(TokenStream, TokenStream)> {
    let mut rev_fk_quotes: Vec<(TokenStream, TokenStream)> = Vec::new();
    let ty = macro_data.ty;

    for (field_ident, fk_annot) in macro_data.get_fk_annotations().iter() {
        if let EntityFieldAnnotation::ForeignKey(table, column) = fk_annot {
            let method_name = format!("search_{table}_childrens");

            // Generate and identifier for the method based on the convention of "search_by__" (note the double underscore)
            // plus the 'table_name' property of the ForeignKey annotation
            let method_name_ident = Ident::new(&method_name, proc_macro2::Span::call_site());
            let method_name_ident_with = Ident::new(
                &format!("{}_with", &method_name),
                proc_macro2::Span::call_site(),
            );
            let quoted_method_signature: TokenStream = quote! {
                async fn #method_name_ident<'a, F: canyon_sql::crud::bounds::ForeignKeyable<F> + Sync + Send>(value: &F) ->
                    Result<Vec<#ty>, Box<(dyn std::error::Error + Sync + Send + 'a)>>
            };
            let quoted_with_method_signature: TokenStream = quote! {
                async fn #method_name_ident_with<'a, F: canyon_sql::crud::bounds::ForeignKeyable<F> + Sync + Send, I> (value: &F, input: I)
                    -> Result<Vec<#ty>, Box<(dyn std::error::Error + Sync + Send + 'a)>>
                where I: canyon_sql::core::DbConnection + Send + 'a
            };

            let f_ident = field_ident.to_string();

            rev_fk_quotes.push((
                quote! { #quoted_method_signature; },
                quote! {
                    /// Given a parent entity T annotated with the derive proc macro `ForeignKeyable`,
                    /// performs a search to find the children that belong to that concrete parent.
                    #quoted_method_signature
                    {
                        let lookage_value = value.get_fk_column(#column)
                            .expect(format!(
                                "Column: {:?} not found in type: {:?}", #column, #table
                            ).as_str());

                        let stmt = format!(
                            "SELECT * FROM {} WHERE {} = $1",
                            #table_schema_data,
                            format!("\"{}\"", #f_ident).as_str()
                        );

                        <#ty as canyon_sql::core::Transaction<#ty>>::query(
                            stmt,
                            &[lookage_value],
                            ""
                        ).await
                    }
                },
            ));

            rev_fk_quotes.push((
                quote! { #quoted_with_method_signature; },
                quote! {
                    /// Given a parent entity T annotated with the derive proc macro `ForeignKeyable`,
                    /// performns a search to find the children that belong to that concrete parent
                    /// with the specified datasource.
                    #quoted_with_method_signature
                    {
                        let lookage_value = value.get_fk_column(#column)
                            .expect(format!(
                                "Column: {:?} not found in type: {:?}", #column, #table
                            ).as_str());

                        let stmt = format!(
                            "SELECT * FROM {} WHERE {} = $1",
                            #table_schema_data,
                            format!("\"{}\"", #f_ident).as_str()
                        );

                        <#ty as canyon_sql::core::Transaction<#ty>>::query(
                            stmt,
                            &[lookage_value],
                            input
                        ).await
                    }
                },
            ));
        }
    }

    rev_fk_quotes
}
