use proc_macro2::TokenStream;
use quote::quote;

use crate::utils::macro_tokens::MacroTokens;

// The API for export to the real macro implementation the generated macros for the READ operations
pub fn generate_read_operations_tokens(
    macro_data: &MacroTokens<'_>,
    table_schema_data: &String,
) -> TokenStream {
    use __details::{count_generators::*, find_all_generators::*};

    let ty = macro_data.ty;
    let mapper_ty = macro_data
        .retrieve_mapping_target_type()
        .expect("Expected mapping target <maps_to>")// TODO: return Err(...)
        .unwrap_or_else(|| ty.clone());

    let fa_stmt = format!("SELECT * FROM {table_schema_data}");
    // TODO: bring the helper and convert the SELECT * into the SELECT col_name, col_name2...?
    // TODO: remember that this queries statements must be autogenerated by some automatic procedure

    let find_all = create_find_all_macro(ty, &mapper_ty, &fa_stmt);
    let find_all_with = create_find_all_with_macro(&fa_stmt, &mapper_ty);
    // let find_all_unchecked = create_find_all_unchecked_macro(ty, &fa_stmt);
    // let find_all_unchecked_with = create_find_all_unchecked_with_macro(ty, &fa_stmt);

    // let count_stmt = format!("SELECT COUNT(*) FROM {table_schema_data}");
    // let count = create_count_macro(ty, &count_stmt);
    // let count_with = create_count_with_macro(ty, &count_stmt);

    let find_by_pk_complex_tokens = generate_find_by_pk_tokens(macro_data, table_schema_data);

    // let read_querybuilder_ops = generate_find_all_query_tokens(macro_data, table_schema_data);

    quote! {
        #find_all
        #find_all_with
        // #find_all_unchecked
        // #find_all_unchecked_with

        // #count
        // #count_with

        // #find_by_pk_complex_tokens

        // #read_querybuilder_ops
    }
}

fn generate_find_all_query_tokens(
    macro_data: &MacroTokens<'_>,
    table_schema_data: &String,
) -> TokenStream {
    let ty = macro_data.ty;

    quote! {
        /// Generates a [`canyon_sql::query::SelectQueryBuilder`]
        /// that allows you to customize the query by adding parameters and constrains dynamically.
        ///
        /// It performs a `SELECT * FROM  table_name`, where `table_name` it's the name of your
        /// entity but converted to the corresponding database convention,
        /// unless concrete values are set on the available parameters of the
        /// `canyon_macro(table_name = "table_name", schema = "schema")`
        fn select_query<'a, R: RowMapper<Output = #ty>>() -> canyon_sql::query::SelectQueryBuilder<'a, #ty> {
            canyon_sql::query::SelectQueryBuilder::new(#table_schema_data, canyon_sql::connection::DatabaseType::default())
        }

        /// Generates a [`canyon_sql::query::SelectQueryBuilder`]
        /// that allows you to customize the query by adding parameters and constrains dynamically.
        ///
        /// It performs a `SELECT * FROM  table_name`, where `table_name` it's the name of your
        /// entity but converted to the corresponding database convention,
        /// unless concrete values are set on the available parameters of the
        /// `canyon_macro(table_name = "table_name", schema = "schema")`
        ///
        /// The query it's made against the database with the configured datasource
        /// described in the configuration file, and selected with the [`&str`]
        /// passed as parameter.
        fn select_query_with<'a, R: RowMapper<Output = #ty>>(database_type: canyon_sql::connection::DatabaseType)
            -> canyon_sql::query::SelectQueryBuilder<'a, #ty>
        {
            canyon_sql::query::SelectQueryBuilder::new(#table_schema_data, database_type)
        }
    }
}

/// Generates the TokenStream for build the __find_by_pk() CRUD operation
fn generate_find_by_pk_tokens(
    macro_data: &MacroTokens<'_>,
    table_schema_data: &String,
) -> TokenStream {
    use __details::pk_generators::*;

    let ty = macro_data.ty;
    let pk = macro_data.get_primary_key_annotation().unwrap_or_default();
    let stmt = format!("SELECT * FROM {table_schema_data} WHERE {pk} = $1");

    // Disabled if there's no `primary_key` annotation
    if pk.is_empty() {
        return quote! {
            async fn find_by_pk<'a, R: RowMapper>(value: &'a dyn canyon_sql::core::QueryParameter<'a>)
                -> Result<Option<R>, Box<(dyn std::error::Error + Send + Sync + 'a)>>
            {
                Err(
                    std::io::Error::new(
                        std::io::ErrorKind::Unsupported,
                        "You can't use the 'find_by_pk' associated function on a \
                        CanyonEntity that does not have a #[primary_key] annotation. \
                        If you need to perform an specific search, use the Querybuilder instead."
                    ).into_inner().unwrap()
                )
            }

            async fn find_by_pk_with<'a, R, I>(
                value: &'a dyn canyon_sql::core::QueryParameter<'a>,
                input: I
            ) -> Result<Option<#ty>, Box<(dyn std::error::Error + Send + Sync + 'a)>>
                where
                    I: canyon_sql::core::DbConnection + Send + 'a,
                    R: RowMapper
            {
                Err(
                    std::io::Error::new(
                        std::io::ErrorKind::Unsupported,
                        "You can't use the 'find_by_pk_with' associated function on a \
                        CanyonEntity that does not have a #[primary_key] annotation. \
                        If you need to perform an specific search, use the Querybuilder instead."
                    ).into_inner().unwrap()
                )
            }
        };
    }

    let find_by_pk = create_find_by_pk_macro(ty, &stmt);
    let find_by_pk_with = create_find_by_pk_with(ty, &stmt);

    quote! {
        #find_by_pk
        #find_by_pk_with
    }
}

mod __details {
    use crate::query_operations::{doc_comments, macro_template::MacroOperationBuilder};
    use proc_macro2::Span;
    use quote::quote;
    use syn::Ident;

    pub mod find_all_generators {
        use super::*;
        use proc_macro2::TokenStream;

        pub fn create_find_all_macro(ty: &syn::Ident, mapper_ty: &syn::Ident, stmt: &str) -> TokenStream {
            quote! {
                async fn find_all()
                    -> Result<Vec<#mapper_ty>, Box<(dyn std::error::Error + Sync + Send)>> {
                    <#ty as canyon_sql::core::Transaction>::query::<&str, #mapper_ty>(
                        #stmt,
                        &[],
                        ""
                    ).await
                }
            }
        }

        pub fn create_find_all_with_macro(stmt: &str, mapper_ty: &syn::Ident) -> TokenStream {
            quote! {
                async fn find_all_with<'a, I>(input: I)
                    -> Result<Vec<#mapper_ty>, Box<(dyn std::error::Error + Sync + Send)>>
                where
                    I: canyon_sql::core::DbConnection + Send + 'a
                {
                    input.query::<&str, #mapper_ty>(#stmt, &[]).await
                }
            }
        }
        //
        // pub fn create_find_all_unchecked_macro(ty: &syn::Ident, stmt: &str) -> TokenStream {
        //     let expect_msg = format!("Failed to execute find all query for: {:?}", ty.to_string());
        //     quote! {
        //         async fn find_all_unchecked<R>() -> Vec<R>
        //             where R: RowMapper,
        //                   Vec<R>: FromIterator<<R as RowMapper>::Output>
        //         {
        //             <#ty as canyon_sql::core::Transaction>::query(#stmt, &[], "")
        //                 .await
        //                 .expect(#expect_msg)
        //         }
        //     }
        // }
        //
        // pub fn create_find_all_unchecked_with_macro(ty: &syn::Ident, stmt: &str) -> TokenStream {
        //     let expect_msg = format!("Failed to execute find all query for: {:?}", ty.to_string());
        //     quote! {
        //         async fn find_all_unchecked_with<'a, R, I>(input: I) -> Vec<R>
        //             where
        //                 R: RowMapper,
        //                 I: canyon_sql::core::DbConnection + Send + 'a,
        //                 Vec<R>: FromIterator<<R as RowMapper>::Output>
        //         {
        //             input.query(#stmt, &[]).await
        //                 .expect(#expect_msg)
        //         }
        //     }
        // }
    }

    pub mod count_generators {
        use super::*;
        use proc_macro2::TokenStream;

        // NOTE: We can't use the QueryOneFor here due that the Tiberius `.get::<i64, usize>(0)` for
        // some reason returns an I32(Some(v)), instead of I64, so we need to manually mapped the wrapped
        // type as i64. Also, we don't have in the count macro datasource info to match it by database,
        // so isn't worth to refactor for the other two drivers and then do some dirty magic on mssql,
        // since we don't distinguish them as the returned type isn't a CanyonRows wrapped one
        fn generate_count_manual_result_handling(ty: &Ident) -> TokenStream {
            let ty_str = ty.to_string();

            quote! {
                #[cfg(feature="postgres")]
                canyon_sql::core::CanyonRows::Postgres(mut v) => Ok(
                    v.remove(0).get::<&str, i64>("count")
                ),
                #[cfg(feature="mssql")]
                canyon_sql::core::CanyonRows::Tiberius(mut v) =>
                    v.remove(0)
                        .get::<i32, usize>(0)
                        .map(|c| c as i64)
                        .ok_or(format!("Failure in the COUNT query for MSSQL for: {}", #ty_str).into())
                        .into(),
                #[cfg(feature="mysql")]
                canyon_sql::core::CanyonRows::MySQL(mut v) => v.remove(0)
                    .get::<i64, usize>(0)
                    .ok_or(format!("Failure in the COUNT query for MYSQL for: {}", #ty_str).into()),
            }
        }

        pub fn create_count_macro(ty: &syn::Ident, stmt: &str) -> TokenStream {
            let result_handling = generate_count_manual_result_handling(ty);

            quote! {
                async fn count() -> Result<i64, Box<(dyn std::error::Error + Sync + Send)>> {
                    let res = <#ty as canyon_sql::core::Transaction>::query_rows(#stmt, &[], "")
                        .await?;
                    match res {
                        #result_handling
                    }
                }
            }
        }

        pub fn create_count_with_macro(ty: &syn::Ident, stmt: &str) -> TokenStream {
            let result_handling = generate_count_manual_result_handling(ty);

            quote! {
                async fn count_with<'a, I>(input: I) -> Result<i64, Box<(dyn std::error::Error + Sync + Send + 'a)>>
                    where I: canyon_sql::core::DbConnection + Send + 'a
                {
                    let res = input.query_rows(#stmt, &[]).await?;

                    match res {
                        #result_handling
                    }
                }
            }
        }
    }

    pub mod pk_generators {
        use super::*;
        use crate::query_operations::macro_template::TransactionMethod;

        pub fn create_find_by_pk_macro(ty: &Ident, stmt: &str) -> MacroOperationBuilder {
            MacroOperationBuilder::new()
                .fn_name("find_by_pk")
                .with_lifetime()
                .type_is_row_mapper()
                .user_type(ty)
                .return_type(ty)
                .add_doc_comment(doc_comments::FIND_BY_PK)
                .add_doc_comment(doc_comments::DS_ADVERTISING)
                .query_string(stmt)
                .input_parameters(quote! { value: &'a dyn canyon_sql::core::QueryParameter<'a> })
                .forwarded_parameters(quote! { vec![value] })
                .with_transaction_method(TransactionMethod::QueryOne)
        }

        pub fn create_find_by_pk_with(ty: &Ident, stmt: &str) -> MacroOperationBuilder {
            MacroOperationBuilder::new()
                .fn_name("find_by_pk_with")
                .type_is_row_mapper()
                .with_input_param()
                .user_type(ty)
                .return_type(ty)
                .add_doc_comment(doc_comments::FIND_BY_PK)
                .add_doc_comment(doc_comments::DS_ADVERTISING)
                .query_string(stmt)
                .input_parameters(quote! { value: &'a dyn canyon_sql::core::QueryParameter<'a> })
                .forwarded_parameters(quote! { vec![value] })
                .with_transaction_method(TransactionMethod::QueryOne)
        }
    }
}

#[cfg(test)]
mod macro_builder_read_ops_tests {
    use super::__details::{count_generators::*, find_all_generators::*, pk_generators::*};
    use crate::query_operations::consts::*;

    const SELECT_ALL_STMT: &str = "SELECT * FROM public.user"; // TODO: introduce the const_format crate
    const COUNT_STMT: &str = "SELECT COUNT(*) FROM public.user";
    const FIND_BY_PK_STMT: &str = "SELECT * FROM public.user WHERE id = $1";

    // #[test]
    // fn test_macro_builder_find_all() {
    //     let find_all_builder = create_find_all_macro(
    //         &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
    //         SELECT_ALL_STMT,
    //     );
    //     let find_all = find_all_builder.to_string();
    //
    //     assert!(find_all.contains("async fn find_all"));
    //     assert!(find_all.contains(RES_RET_TY));
    // }
    //
    // #[test]
    // fn test_macro_builder_find_all_with() {
    //     let find_all_builder = create_find_all_with_macro(
    //         SELECT_ALL_STMT,
    //     );
    //     let find_all_with = find_all_builder.to_string();
    //
    //     assert!(find_all_with.contains("async fn find_all_with"));
    //     assert!(find_all_with.contains(RES_RET_TY_LT));
    //     assert!(find_all_with.contains(LT_CONSTRAINT));
    //     assert!(find_all_with.contains(WITH_WHERE_BOUNDS));
    // }
    //
    // #[test]
    // fn test_macro_builder_find_all_unchecked() {
    //     let find_all_unc_builder = create_find_all_unchecked_macro(
    //         &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
    //         SELECT_ALL_STMT,
    //     );
    //     let find_all_unc = find_all_unc_builder.to_string();
    //
    //     assert!(find_all_unc.contains("async fn find_all_unchecked"));
    //     assert!(find_all_unc.contains(RAW_RET_TY));
    // }
    //
    // #[test]
    // fn test_macro_builder_find_all_unchecked_with() {
    //     let find_all_unc_with_builder = create_find_all_unchecked_with_macro(
    //         &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
    //         &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
    //         SELECT_ALL_STMT,
    //     );
    //     let find_all_unc_with = find_all_unc_with_builder.to_string();
    //
    //     assert!(find_all_unc_with.contains("async fn find_all_unchecked_with"));
    //     assert!(find_all_unc_with.contains(RAW_RET_TY));
    //     assert!(find_all_unc_with.contains(LT_CONSTRAINT));
    //     assert!(find_all_unc_with.contains(INPUT_PARAM));
    // }

    #[test]
    fn test_macro_builder_count() {
        let count_builder = create_count_macro(
            &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
            COUNT_STMT,
        );
        let count = count_builder.to_string();

        assert!(count.contains("async fn count"));
        assert!(count.contains("Result < i64"));
    }

    #[test]
    fn test_macro_builder_count_with() {
        let count_with_builder = create_count_with_macro(
            &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
            COUNT_STMT,
        );
        let count_with = count_with_builder.to_string();

        assert!(count_with.contains("async fn count_with"));
        assert!(count_with.contains("Result < i64"));
        assert!(count_with.contains(LT_CONSTRAINT));
        assert!(count_with.contains(INPUT_PARAM));
    }

    #[test]
    fn test_macro_builder_find_by_pk() {
        let find_by_pk_builder = create_find_by_pk_macro(
            &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
            FIND_BY_PK_STMT,
        );
        let find_by_pk = find_by_pk_builder.generate_tokens().to_string();

        assert!(find_by_pk.contains("async fn find_by_pk"));
        assert!(find_by_pk.contains(LT_CONSTRAINT));
        assert!(find_by_pk.contains(OPT_RET_TY_LT));
    }

    #[test]
    fn test_macro_builder_find_by_pk_with() {
        let find_by_pk_with_builder = create_find_by_pk_with(
            &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
            FIND_BY_PK_STMT,
        );
        let find_by_pk_with = find_by_pk_with_builder.generate_tokens().to_string();

        assert!(find_by_pk_with.contains("async fn find_by_pk_with"));
        assert!(find_by_pk_with.contains(LT_CONSTRAINT));
        assert!(find_by_pk_with.contains(INPUT_PARAM));
        assert!(find_by_pk_with.contains(OPT_RET_TY_LT));
    }
}
