use crate::query_operations::consts;
use crate::utils::macro_tokens::MacroTokens;
use proc_macro2::{Ident, TokenStream};
use quote::quote;

/// Facade function that acts as the unique API for export to the real macro implementation
/// of all the generated macros for the READ operations
pub fn generate_read_operations_tokens(
    macro_data: &MacroTokens<'_>,
    table_schema_data: &String,
) -> TokenStream {
    let ty = macro_data.ty;
    let mapper_ty = macro_data
        .retrieve_mapping_target_type()
        .expect("Expected mapping target <maps_to>") // TODO: return Err(...)
        .unwrap_or_else(|| ty.clone());

    let find_all_tokens = generate_find_all_operations_tokens(ty, &mapper_ty, table_schema_data);
    let count_tokens = generate_count_operations_tokens(ty, table_schema_data);
    let find_by_pk_tokens = generate_find_by_pk_operations_tokens(macro_data, table_schema_data);
    let read_querybuilder_ops = generate_select_querybuilder_tokens(table_schema_data);

    quote! {
        #find_all_tokens
        #read_querybuilder_ops
        #count_tokens
        #find_by_pk_tokens
    }
}

fn generate_find_all_operations_tokens(
    ty: &Ident,
    mapper_ty: &Ident,
    table_schema_data: &String,
) -> TokenStream {
    let fa_stmt = format!("SELECT * FROM {table_schema_data}");

    // TODO: bring the helper and convert the SELECT * into the SELECT col_name, col_name2...?
    // TODO: remember that this queries statements must be autogenerated by some automatic procedure

    let find_all = __details::find_all_generators::create_find_all_macro(ty, mapper_ty, &fa_stmt);
    let find_all_with =
        __details::find_all_generators::create_find_all_with_macro(mapper_ty, &fa_stmt);

    quote! {
        #find_all
        #find_all_with
    }
}

fn generate_select_querybuilder_tokens(table_schema_data: &String) -> TokenStream {
    quote! {
        /// Generates a [`canyon_sql::query::querybuilder::SelectQueryBuilder`]
        /// that allows you to customize the query by adding parameters and constrains dynamically.
        ///
        /// It generates a Query `SELECT * FROM  table_name`, where `table_name` it's the name of your
        /// entity but converted to the corresponding database convention,
        /// unless concrete values are set on the available parameters of the
        /// `canyon_macro(table_name = "table_name", schema = "schema")`
        fn select_query<'a>()
            -> Result<
                canyon_sql::query::querybuilder::SelectQueryBuilder<'a>,
                Box<(dyn std::error::Error + Send + Sync + 'a)>
            >
        {
            canyon_sql::query::querybuilder::SelectQueryBuilder::new(#table_schema_data, canyon_sql::connection::DatabaseType::default_type()?)
        }

        /// Generates a [`canyon_sql::query::querybuilder::SelectQueryBuilder`]
        /// that allows you to customize the query by adding parameters and constrains dynamically.
        ///
        /// It generates a Query `SELECT * FROM  table_name`, where `table_name` it's the name of your
        /// entity but converted to the corresponding database convention,
        /// unless concrete values are set on the available parameters of the
        /// `canyon_macro(table_name = "table_name", schema = "schema")`
        fn select_query_with<'a>(database_type: canyon_sql::connection::DatabaseType)
            -> Result<
                canyon_sql::query::querybuilder::SelectQueryBuilder<'a>,
                Box<(dyn std::error::Error + Send + Sync + 'a)>
        > {
            canyon_sql::query::querybuilder::SelectQueryBuilder::new(#table_schema_data, database_type)
        }
    }
}

fn generate_count_operations_tokens(ty: &Ident, table_schema_data: &String) -> TokenStream {
    let count_stmt = format!("SELECT COUNT(*) FROM {table_schema_data}");
    let count = __details::count_generators::create_count_macro(ty, &count_stmt);
    let count_with = __details::count_generators::create_count_with_macro(ty, &count_stmt);

    quote! {
        #count
        #count_with
    }
}

fn generate_find_by_pk_operations_tokens(
    macro_data: &MacroTokens<'_>,
    table_schema_data: &String,
) -> TokenStream {
    let ty = macro_data.ty;
    let mapper_ty = macro_data
        .retrieve_mapping_target_type()
        .expect("Expected mapping target <maps_to>")
        .unwrap_or_else(|| ty.clone());
    let pk = macro_data.get_primary_key_annotation();
    let no_pk_runtime_err = if pk.is_some() {
        None
    } else {
        let err_msg = consts::FIND_BY_PK_ERR_NO_PK;
        Some(quote! {
            Err(
                std::io::Error::new(
                    std::io::ErrorKind::Unsupported,
                    #err_msg,
                ).into_inner().unwrap()
            )
        })
    };
    let stmt = format!(
        "SELECT * FROM {table_schema_data} WHERE {} = $1",
        pk.unwrap_or_default()
    );

    let find_by_pk = __details::find_by_pk_generators::create_find_by_pk_macro(
        ty,
        &mapper_ty,
        &stmt,
        &no_pk_runtime_err,
    );
    let find_by_pk_with =
        __details::find_by_pk_generators::create_find_by_pk_with(ty, &stmt, &no_pk_runtime_err);

    quote! {
        #find_by_pk
        #find_by_pk_with
    }
}

mod __details {
    use quote::quote;
    use syn::Ident;

    pub mod find_all_generators {
        use super::*;
        use proc_macro2::TokenStream;

        pub fn create_find_all_macro(ty: &Ident, mapper_ty: &Ident, stmt: &str) -> TokenStream {
            quote! {
                async fn find_all()
                    -> Result<Vec<#mapper_ty>, Box<(dyn std::error::Error + Send + Sync)>> {
                    <#ty as canyon_sql::core::Transaction>::query::<&str, #mapper_ty>(
                        #stmt,
                        &[],
                        ""
                    ).await
                }
            }
        }

        pub fn create_find_all_with_macro(mapper_ty: &Ident, stmt: &str) -> TokenStream {
            quote! {
                async fn find_all_with<'a, I>(input: I)
                    -> Result<Vec<#mapper_ty>, Box<(dyn std::error::Error + Send + Sync)>>
                where
                    I: canyon_sql::connection::DbConnection + Send + 'a
                {
                    input.query::<&str, #mapper_ty>(#stmt, &[]).await
                }
            }
        }
    }

    pub mod count_generators {
        use super::*;
        use proc_macro2::TokenStream;

        // NOTE: We can't use the QueryOneFor here due that the Tiberius `.get::<i64, usize>(0)` for
        // some reason returns an I32(Some(v)), instead of I64, so we need to manually mapped the wrapped
        // type as i64. Also, we don't have in the count macro datasource info to match it by database,
        // so isn't worth to refactor for the other two drivers and then do some dirty magic on mssql,
        // since we don't distinguish them as the returned type isn't a CanyonRows wrapped one
        fn generate_count_manual_result_handling(ty: &Ident) -> TokenStream {
            let ty_str = ty.to_string();

            quote! {
                #[cfg(feature="postgres")]
                canyon_sql::core::CanyonRows::Postgres(mut v) => Ok(
                    v.remove(0).get::<&str, i64>("count")
                ),
                #[cfg(feature="mssql")]
                canyon_sql::core::CanyonRows::Tiberius(mut v) =>
                    v.remove(0)
                        .get::<i32, usize>(0)
                        .map(|c| c as i64)
                        .ok_or(format!("Failure in the COUNT query for MSSQL for: {}", #ty_str).into())
                        .into(),
                #[cfg(feature="mysql")]
                canyon_sql::core::CanyonRows::MySQL(mut v) => v.remove(0)
                    .get::<i64, usize>(0)
                    .ok_or(format!("Failure in the COUNT query for MYSQL for: {}", #ty_str).into()),
            }
        }

        pub fn create_count_macro(ty: &syn::Ident, stmt: &str) -> TokenStream {
            let result_handling = generate_count_manual_result_handling(ty);

            quote! {
                async fn count() -> Result<i64, Box<(dyn std::error::Error + Send + Sync)>> {
                    let res = <#ty as canyon_sql::core::Transaction>::query_rows(#stmt, &[], "")
                        .await?;
                    match res {
                        #result_handling
                    }
                }
            }
        }

        pub fn create_count_with_macro(ty: &syn::Ident, stmt: &str) -> TokenStream {
            let result_handling = generate_count_manual_result_handling(ty);

            quote! {
                async fn count_with<'a, I>(input: I) -> Result<i64, Box<(dyn std::error::Error + Send + Sync + 'a)>>
                    where I: canyon_sql::connection::DbConnection + Send + 'a
                {
                    let res = input.query_rows(#stmt, &[]).await?;

                    match res {
                        #result_handling
                    }
                }
            }
        }
    }

    pub mod find_by_pk_generators {
        use super::*;
        use proc_macro2::TokenStream;

        pub fn create_find_by_pk_macro(
            ty: &Ident,
            mapper_ty: &syn::Ident,
            stmt: &str,
            pk_runtime_error: &Option<TokenStream>,
        ) -> TokenStream {
            let body = if pk_runtime_error.is_none() {
                quote! {
                    <#ty as canyon_sql::core::Transaction>::query_one::<
                        &str,
                        &[&'a (dyn QueryParameter<'a>)],
                        #mapper_ty
                    >(#stmt, &[value], "").await
                }
            } else {
                quote! { #pk_runtime_error }
            };

            quote! {
                async fn find_by_pk<'a>(value: &'a dyn canyon_sql::query::QueryParameter<'a>)
                    -> Result<Option<#mapper_ty>, Box<(dyn std::error::Error + Send + Sync + 'a)>>
                {
                    #body
                }
            }
        }

        pub fn create_find_by_pk_with(
            mapper_ty: &syn::Ident,
            stmt: &str,
            pk_runtime_error: &Option<TokenStream>,
        ) -> TokenStream {
            let body = if pk_runtime_error.is_none() {
                quote! {
                    input.query_one::<#mapper_ty>(#stmt, &[value]).await
                }
            } else {
                quote! { #pk_runtime_error }
            };

            quote! {
                async fn find_by_pk_with<'a, I>(value: &'a dyn canyon_sql::query::QueryParameter<'a>, input: I)
                    -> Result<Option<#mapper_ty>, Box<(dyn std::error::Error + Send + Sync + 'a)>>
                where
                    I: canyon_sql::connection::DbConnection + Send + 'a
                {
                    #body
                }
            }
        }
    }
}

#[cfg(test)]
mod macro_builder_read_ops_tests {
    use super::__details::{count_generators::*, find_all_generators::*};

    use crate::query_operations::consts;
    use crate::query_operations::read::__details::find_by_pk_generators::{
        create_find_by_pk_macro, create_find_by_pk_with,
    };
    use proc_macro2::Ident;

    const SELECT_ALL_STMT: &str = "SELECT * FROM public.user"; // TODO: introduce the const_format crate
    const COUNT_STMT: &str = "SELECT COUNT(*) FROM public.user";
    const FIND_BY_PK_STMT: &str = "SELECT * FROM public.user WHERE id = $1";

    #[test]
    fn test_create_find_all_macro() {
        let ty = syn::parse_str::<Ident>("User").unwrap();
        let mapper_ty = syn::parse_str::<Ident>("User").unwrap();
        let tokens = create_find_all_macro(&ty, &mapper_ty, SELECT_ALL_STMT);
        let generated = tokens.to_string();

        assert!(generated.contains("async fn find_all"));
        assert!(generated.contains(consts::RES_RET_TY));
        assert!(generated.contains(SELECT_ALL_STMT));
    }

    #[test]
    fn test_create_find_all_with_macro() {
        let mapper_ty = syn::parse_str::<Ident>("User").unwrap();
        let tokens = create_find_all_with_macro(&mapper_ty, SELECT_ALL_STMT);
        let generated = tokens.to_string();

        assert!(generated.contains("async fn find_all_with"));
        assert!(generated.contains(consts::RES_RET_TY));
        assert!(generated.contains(consts::LT_CONSTRAINT));
        assert!(generated.contains(consts::INPUT_PARAM));
        assert!(generated.contains(SELECT_ALL_STMT));
    }

    #[test]
    fn test_create_count_macro() {
        let ty = syn::parse_str::<Ident>("User").unwrap();
        let tokens = create_count_macro(&ty, COUNT_STMT);
        let generated = tokens.to_string();

        assert!(generated.contains("async fn count"));
        assert!(generated.contains(consts::I64_RET_TY));
        assert!(generated.contains(COUNT_STMT));
    }

    #[test]
    fn test_create_count_with_macro() {
        let ty = syn::parse_str::<Ident>("User").unwrap();
        let tokens = create_count_with_macro(&ty, COUNT_STMT);
        let generated = tokens.to_string();

        assert!(generated.contains("async fn count_with"));
        assert!(generated.contains(consts::I64_RET_TY_LT));
        assert!(generated.contains(COUNT_STMT));
        assert!(generated.contains(consts::LT_CONSTRAINT));
        assert!(generated.contains(consts::INPUT_PARAM));
    }

    #[test]
    fn test_create_find_by_pk_macro() {
        let ty = syn::parse_str::<Ident>("User").unwrap();
        let mapper_ty = syn::parse_str::<Ident>("User").unwrap();
        let pk_runtime_error = None;
        let tokens = create_find_by_pk_macro(&ty, &mapper_ty, FIND_BY_PK_STMT, &pk_runtime_error);
        let generated = tokens.to_string();

        assert!(generated.contains("async fn find_by_pk"));
        assert!(generated.contains(consts::OPT_RET_TY_LT));
        assert!(generated.contains(FIND_BY_PK_STMT));
    }

    #[test]
    fn test_create_find_by_pk_with_macro() {
        let mapper_ty = syn::parse_str::<Ident>("User").unwrap();
        let pk_runtime_error = None;
        let tokens = create_find_by_pk_with(&mapper_ty, FIND_BY_PK_STMT, &pk_runtime_error);
        let generated = tokens.to_string();

        assert!(generated.contains("async fn find_by_pk_with"));
        assert!(generated.contains(consts::OPT_RET_TY_LT));
        assert!(generated.contains(consts::LT_CONSTRAINT));
        assert!(generated.contains(FIND_BY_PK_STMT));
    }
}
