use canyon_entities::field_annotation::EntityFieldAnnotation;

use proc_macro2::{Span, TokenStream};
use quote::quote;

use crate::query_operations::macro_template::MacroOperationBuilder;
use crate::utils::helpers::*;
use crate::utils::macro_tokens::MacroTokens;

// The API for export to the real macro implementation the generated macros for the READ operations
pub fn generate_read_operations_tokens(
    macro_data: &MacroTokens<'_>,
    table_schema_data: &String,
) -> TokenStream {
    use __details::{count_generators::*, find_all_generators::*};

    let ty = macro_data.ty;
    let fa_stmt = format!("SELECT * FROM {table_schema_data}");
    // TODO: bring the helper and convert the SELECT * into the
    // SELECT col_name, col_name2...?
    // TODO: remember that this queries statements must be autogenerated by some automatic procedure

    let find_all = create_find_all_macro(ty, &fa_stmt);
    let find_all_with = create_find_all_with_macro(ty, &fa_stmt);
    let find_all_unchecked = create_find_all_unchecked_macro(ty, &fa_stmt);
    let find_all_unchecked_with = create_find_all_unchecked_with_macro(ty, &fa_stmt);

    let count_stmt = format!("SELECT COUNT(*) FROM {table_schema_data}");
    let count = create_count_macro(ty, &count_stmt);
    let count_with = create_count_with_macro(ty, &count_stmt);

    let find_by_pk_complex_tokens = generate_find_by_pk_tokens(macro_data, table_schema_data);

    quote! {
        #find_all
        #find_all_with
        #find_all_unchecked
        #find_all_unchecked_with

        #count
        #count_with

        #find_by_pk_complex_tokens
    }
}

pub fn generate_find_all_query_tokens(
    macro_data: &MacroTokens<'_>,
    table_schema_data: &String,
) -> TokenStream {
    let ty = macro_data.ty;

    quote! {
        /// Generates a [`canyon_sql::query::SelectQueryBuilder`]
        /// that allows you to customize the query by adding parameters and constrains dynamically.
        ///
        /// It performs a `SELECT * FROM  table_name`, where `table_name` it's the name of your
        /// entity but converted to the corresponding database convention,
        /// unless concrete values are set on the available parameters of the
        /// `canyon_macro(table_name = "table_name", schema = "schema")`
        fn select_query<'a>() -> canyon_sql::query::SelectQueryBuilder<'a, #ty, &'a str> {
            canyon_sql::query::SelectQueryBuilder::new(#table_schema_data, "")
        }

        /// Generates a [`canyon_sql::query::SelectQueryBuilder`]
        /// that allows you to customize the query by adding parameters and constrains dynamically.
        ///
        /// It performs a `SELECT * FROM  table_name`, where `table_name` it's the name of your
        /// entity but converted to the corresponding database convention,
        /// unless concrete values are set on the available parameters of the
        /// `canyon_macro(table_name = "table_name", schema = "schema")`
        ///
        /// The query it's made against the database with the configured datasource
        /// described in the configuration file, and selected with the [`&str`]
        /// passed as parameter.
        fn select_query_with<'a, I>(input: I) -> canyon_sql::query::SelectQueryBuilder<'a, #ty, I>
            where I: canyon_sql::core::DbConnection + Send + 'a
        {
            canyon_sql::query::SelectQueryBuilder::new(#table_schema_data, input)
        }
    }
}

/// Generates the TokenStream for build the __find_by_pk() CRUD operation
fn generate_find_by_pk_tokens(
    macro_data: &MacroTokens<'_>,
    table_schema_data: &String,
) -> TokenStream {
    use __details::pk_generators::*;

    let ty = macro_data.ty;
    let pk = macro_data.get_primary_key_annotation().unwrap_or_default();
    let stmt = format!("SELECT * FROM {table_schema_data} WHERE {pk} = $1");

    // Disabled if there's no `primary_key` annotation
    if pk.is_empty() {
        return quote! {
            async fn find_by_pk<'a>(value: &'a dyn canyon_sql::core::QueryParameter<'a>)
                -> Result<Option<#ty>, Box<(dyn std::error::Error + Send + Sync + 'a)>>
            {
                Err(
                    std::io::Error::new(
                        std::io::ErrorKind::Unsupported,
                        "You can't use the 'find_by_pk' associated function on a \
                        CanyonEntity that does not have a #[primary_key] annotation. \
                        If you need to perform an specific search, use the Querybuilder instead."
                    ).into_inner().unwrap()
                )
            }

            async fn find_by_pk_with<'a, I>(
                value: &'a dyn canyon_sql::core::QueryParameter<'a>,
                input: I
            ) -> Result<Option<#ty>, Box<(dyn std::error::Error + Send + Sync + 'a)>>
                    where I: canyon_sql::core::DbConnection + Send + 'a,
            {
                Err(
                    std::io::Error::new(
                        std::io::ErrorKind::Unsupported,
                        "You can't use the 'find_by_pk_with' associated function on a \
                        CanyonEntity that does not have a #[primary_key] annotation. \
                        If you need to perform an specific search, use the Querybuilder instead."
                    ).into_inner().unwrap()
                )
            }
        };
    }

    // TODO: this can be functionally handled, instead of this impl
    let result_handling = quote! {
        n if n.len() == 0 => Ok(None),
        _ => Ok(
            Some(transaction_result.into_results::<#ty>().remove(0))
        )
    };

    let find_by_pk = create_find_by_pk_macro(ty, &stmt, &result_handling);
    let find_by_pk_with = create_find_by_pk_with(ty, &stmt, &result_handling);

    quote! {
        #find_by_pk
        #find_by_pk_with
    }
}

mod __details {
    use crate::query_operations::{doc_comments, macro_template::MacroOperationBuilder};
    use proc_macro2::Span;
    use quote::quote;
    use syn::Ident;

    pub mod find_all_generators {
        use super::*;

        pub fn create_find_all_macro(ty: &syn::Ident, stmt: &str) -> MacroOperationBuilder {
            MacroOperationBuilder::new()
                .fn_name("find_all")
                .user_type(ty)
                .return_type(ty)
                .add_doc_comment("Executes a 'SELECT * FROM <user_type>'")
                .add_doc_comment("This operation retrieves all the users records stored with the default datasource")
                .query_string(stmt)
        }

        pub fn create_find_all_with_macro(ty: &syn::Ident, stmt: &str) -> MacroOperationBuilder {
            MacroOperationBuilder::new()
                .fn_name("find_all_with")
                .with_input_param()
                .user_type(ty)
                .return_type(ty)
                .add_doc_comment("Executes a 'SELECT * FROM <user_type>'")
                .add_doc_comment("This operation retrieves all the users records stored with the provided datasource")
                .query_string(stmt)
        }

        pub fn create_find_all_unchecked_macro(
            ty: &syn::Ident,
            stmt: &str,
        ) -> MacroOperationBuilder {
            MacroOperationBuilder::new()
                .fn_name("find_all_unchecked")
                .user_type(ty)
                .return_type(ty)
                .add_doc_comment("Executes a 'SELECT * FROM <user_type>'")
                .add_doc_comment("This operation retrieves all the users records stored with the provided datasource")
                .query_string(stmt)
                .with_unwrap()
        }

        pub fn create_find_all_unchecked_with_macro(
            ty: &syn::Ident,
            stmt: &str,
        ) -> MacroOperationBuilder {
            MacroOperationBuilder::new()
                .fn_name("find_all_unchecked_with")
                .user_type(ty)
                .return_type(ty)
                .with_input_param()
                .add_doc_comment("Executes a 'SELECT * FROM <user_type>'")
                .add_doc_comment("This operation retrieves all the users records stored with the provided datasource")
                .query_string(stmt)
                .with_unwrap()
        }
    }

    pub mod count_generators {
        use proc_macro2::TokenStream;

        use super::*;

        fn generate_count_manual_result_handling(ty: &Ident) -> TokenStream {
            let ty_str = ty.to_string();

            quote! {
                #[cfg(feature="postgres")]
                canyon_sql::core::CanyonRows::Postgres(mut v) => Ok(
                    v.remove(0).get::<&str, i64>("count")
                ),
                #[cfg(feature="mssql")]
                canyon_sql::core::CanyonRows::Tiberius(mut v) =>
                    v.remove(0)
                        .get::<i32, usize>(0)
                        .map(|c| c as i64)
                        .ok_or(format!("Failure in the COUNT query for MSSQL for: {}", #ty_str).into())
                        .into(),
                #[cfg(feature="mysql")]
                canyon_sql::core::CanyonRows::MySQL(mut v) => v.remove(0)
                    .get::<i64, usize>(0)
                    .ok_or(format!("Failure in the COUNT query for MYSQL for: {}", #ty_str).into()),

                _ => panic!() // TODO remove when the generics will be refactored
            }
        }

        pub fn create_count_macro(ty: &syn::Ident, stmt: &str) -> MacroOperationBuilder {
            let result_handling = generate_count_manual_result_handling(ty);

            MacroOperationBuilder::new()
                .fn_name("count")
                .user_type(ty)
                .return_type(&syn::Ident::new("i64", Span::call_site())) // TODO: into ident or take by value
                .add_doc_comment(
                    "Performs a COUNT(*) query over the table related to the entity T'",
                )
                .add_doc_comment("Executed with the default datasource")
                .query_string(stmt)
                .transaction_as_variable(quote! {
                    match transaction_result { // NOTE: dark magic. Should be refactored
                        #result_handling
                    }
                })
                .propagate_transaction_result()
                .disable_mapping()
                .raw_return()
        }

        pub fn create_count_with_macro(ty: &syn::Ident, stmt: &str) -> MacroOperationBuilder {
            let result_handling = generate_count_manual_result_handling(ty);

            MacroOperationBuilder::new()
                .fn_name("count_with")
                .user_type(ty)
                .with_input_param()
                .return_type(&syn::Ident::new("i64", Span::call_site())) // TODO: into ident or take by value
                .add_doc_comment(
                    "Performs a COUNT(*) query over the table related to the entity T'",
                )
                .add_doc_comment("It will be executed with the specified datasource")
                .query_string(stmt)
                .transaction_as_variable(quote! {
                    match transaction_result {
                        #result_handling
                    }
                })
                .propagate_transaction_result()
                .disable_mapping()
                .raw_return()
        }
    }

    pub mod pk_generators {
        use proc_macro2::TokenStream;

        use super::*;

        pub fn create_find_by_pk_macro(
            ty: &Ident,
            stmt: &str,
            result_handling: &TokenStream,
        ) -> MacroOperationBuilder {
            MacroOperationBuilder::new()
                .fn_name("find_by_pk")
                .with_lifetime()
                .user_type(ty)
                .return_type(ty)
                .add_doc_comment(doc_comments::FIND_BY_PK)
                .add_doc_comment(doc_comments::DS_ADVERTISING)
                .query_string(stmt)
                .input_parameters(quote! { value: &'a dyn canyon_sql::core::QueryParameter<'a> })
                .forwarded_parameters(quote! { vec![value] })
                .propagate_transaction_result()
                .disable_mapping()
                .single_result()
                .transaction_as_variable(quote! {
                    match transaction_result { // NOTE: dark magic. Should be refactored
                        #result_handling
                    }
                })
        }

        pub fn create_find_by_pk_with(
            ty: &Ident,
            stmt: &str,
            result_handling: &TokenStream,
        ) -> MacroOperationBuilder {
            MacroOperationBuilder::new()
                .fn_name("find_by_pk_with")
                .with_input_param()
                .user_type(ty)
                .return_type(ty)
                .add_doc_comment(doc_comments::FIND_BY_PK)
                .add_doc_comment(doc_comments::DS_ADVERTISING)
                .query_string(stmt)
                .input_parameters(quote! { value: &'a dyn canyon_sql::core::QueryParameter<'a> })
                .forwarded_parameters(quote! { vec![value] })
                .propagate_transaction_result()
                .disable_mapping()
                .single_result()
                .transaction_as_variable(quote! {
                    match transaction_result { // NOTE: dark magic. Should be refactored
                        #result_handling
                    }
                })
        }
    }
}

#[cfg(test)]
mod macro_builder_read_ops_tests {
    use super::__details::{count_generators::*, find_all_generators::*, pk_generators::*};
    use crate::query_operations::tests_consts::*;
    use proc_macro2::Span;
    use quote::quote;
    use syn::Ident;

    const SELECT_ALL_STMT: &str = "SELECT * FROM public.user"; // TODO: introduce the const_format crate
    const COUNT_STMT: &str = "SELECT COUNT(*) FROM public.user";
    const FIND_BY_PK_STMT: &str = "SELECT * FROM public.user WHERE id = $1";

    #[test]
    fn test_macro_builder_find_all() {
        let find_all_builder = create_find_all_macro(
            &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
            SELECT_ALL_STMT
        );
        let find_all = find_all_builder.generate_tokens().to_string();

        assert!(find_all.contains("async fn find_all"));
        assert!(find_all.contains(RES_RET_TY));
    }

    #[test]
    fn test_macro_builder_find_all_with() {
        let find_all_builder = create_find_all_with_macro(
            &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
            SELECT_ALL_STMT
        );
        let find_all_with = find_all_builder.generate_tokens().to_string();

        assert!(find_all_with.contains("async fn find_all_with"));
        assert!(find_all_with.contains(RES_RET_TY_LT));
        assert!(find_all_with.contains(LT_CONSTRAINT));
        assert!(find_all_with.contains(WITH_WHERE_BOUNDS));
    }

    #[test]
    fn test_macro_builder_find_all_unchecked() {
        let find_all_unc_builder = create_find_all_unchecked_macro(
            &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
            SELECT_ALL_STMT
        );
        let find_all_unc = find_all_unc_builder.generate_tokens().to_string();

        assert!(find_all_unc.contains("async fn find_all_unchecked"));
        assert!(find_all_unc.contains(RAW_RET_TY));
    }

    #[test]
    fn test_macro_builder_find_all_unchecked_with() {
        let find_all_unc_with_builder = create_find_all_unchecked_with_macro(
            &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
            SELECT_ALL_STMT
        );
        let find_all_unc_with = find_all_unc_with_builder.generate_tokens().to_string();

        assert!(find_all_unc_with.contains("async fn find_all_unchecked_with"));
        assert!(find_all_unc_with.contains(RAW_RET_TY));
        assert!(find_all_unc_with.contains(LT_CONSTRAINT));
        assert!(find_all_unc_with.contains(INPUT_PARAM));
    }

    #[test]
    fn test_macro_builder_count() {
        let count_builder = create_count_macro(
            &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
            COUNT_STMT
        );
        let count = count_builder.generate_tokens().to_string();

        assert!(count.contains("async fn count"));
        assert!(count.contains("Result < i64"));
    }

    #[test]
    fn test_macro_builder_count_with() {
        let count_with_builder = create_count_with_macro(
            &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
            COUNT_STMT
        );
        let count_with = count_with_builder.generate_tokens().to_string();

        assert!(count_with.contains("async fn count_with"));
        assert!(count_with.contains("Result < i64"));
        assert!(count_with.contains(LT_CONSTRAINT));
        assert!(count_with.contains(INPUT_PARAM));
    }

    #[test]
    fn test_macro_builder_find_by_pk() {
        let find_by_pk_builder = create_find_by_pk_macro(
            &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
            FIND_BY_PK_STMT, 
            &quote! {}
        );
        let find_by_pk = find_by_pk_builder.generate_tokens().to_string();

        assert!(find_by_pk.contains("async fn find_by_pk"));
        assert!(find_by_pk.contains(LT_CONSTRAINT));
        assert!(find_by_pk.contains(OPT_RET_TY_LT));
    }

    #[test]
    fn test_macro_builder_find_by_pk_with() {
        let find_by_pk_with_builder = create_find_by_pk_with(
            &USER_MOCK_TY.with(|user_mock_ty| user_mock_ty.borrow().clone()),
            FIND_BY_PK_STMT, 
            &quote! {}
        );
        let find_by_pk_with = find_by_pk_with_builder.generate_tokens().to_string();

        assert!(find_by_pk_with.contains("async fn find_by_pk_with"));
        assert!(find_by_pk_with.contains(LT_CONSTRAINT));
        assert!(find_by_pk_with.contains(INPUT_PARAM));
        assert!(find_by_pk_with.contains(OPT_RET_TY_LT));
    }
}
