use crate::query::parameters::QueryParameter;
use crate::query::querybuilder::syntax::column::ColumnRef;
use crate::rows::FromSqlOwnedValue;

/// Contract that provides a way to Canyon to inspect certain property or values at runtime.
///
/// Typically, these will be used by the macros to gather some information or to create some user code
/// in more complex scenarios, like when insert an entity, when we need to know the value of the fields of
/// the current instance that we'd like to insert
pub trait Inspectionable<'a> {
    // TODO: change name to entity runtime info EntityRuntimeInfo
    type PrimaryKeyType: FromSqlOwnedValue<Self::PrimaryKeyType>;

    /// Returns an allocated linear collection with the current values of all the fields declared
    /// for the implementor, as the result of the evaluation of the &self.#field expression, iteratively
    /// over every type member, but if the type contains in some field the #[primary_key] annotation,
    /// this will be skipped!!
    ///
    /// This is mostly because this operation now is only useful on the insert_entity family operations,
    /// and is a fixed invariant in our logic nowadays.
    ///
    /// # Warning
    /// This may change in the future, so that's why this operation shouldn't be used, nor it's
    /// recommended to use it publicly as an end-user.
    fn fields_actual_values(&self) -> Vec<&dyn QueryParameter>;

    /// Returns a linear collection with the names of every field for the implementor as a String
    fn fields_names(&self) -> &[&'static str];
    fn fields_as_column_refs(&self) -> Vec<ColumnRef<'static>>;

    fn queries_placeholders(&self) -> &'static str;

    fn primary_key(&self) -> Option<&'static str>;
    fn primary_key_st() -> Option<&'static str>;
    fn primary_key_actual_value(&self) -> &'_ (dyn QueryParameter + '_);
    fn set_primary_key_actual_value(
        &mut self,
        value: Self::PrimaryKeyType,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>>;
    fn primary_key_as_column_ref(&self) -> Option<ColumnRef<'static>>;
}

pub trait TableMetadata<'a>: std::fmt::Display {
    fn as_str(&self) -> &'a str;
}

/// Created for retrieve the field's name of a field of a struct, giving
/// the Canyon's autogenerated enum with the variants that maps this
/// fields.
///
/// ```
/// pub struct Struct<'a> {
///     pub some_field: &'a str
/// }
///
/// // Autogenerated enum
/// #[derive(Debug)]
/// #[allow(non_camel_case_types)]
/// pub enum StructField {
///     some_field
/// }
/// ```
/// So, to retrieve the field's name, something like this w'd be used on some part
/// of the Canyon's Manager crate, to wire the necessary code to pass the field
/// name, retrieved from the enum variant, to a called.
///
/// // Something like:
/// `let struct_field_name_from_variant = StructField::some_field.field_name_as_str();`
pub trait FieldIdentifier: std::fmt::Display {
    fn as_str(&self) -> &'static str;

    fn as_column_ref(&self) -> ColumnRef<'static>;
}

/// Represents some kind of introspection to make the implementors
/// able to retrieve a value inside some variant of an associated enum type.
/// and convert it to a tuple struct formed by the column name as an String,
/// and the dynamic value of the [`QueryParameter`] trait object contained
/// inside the variant requested,
/// enabling a conversion of that value into something
/// that can be part of an SQL query.
///
///
/// Ex:
/// `SELECT * FROM some_table WHERE id = 2`
///
/// That '2' it's extracted from some enum that implements [`FieldValueIdentifier`],
/// where usually the variant w'd be something like:
///
/// ```
/// pub enum Enum {
///     IntVariant(i32)
/// }
/// ```
pub trait FieldValueIdentifier {
    fn value(&self) -> (ColumnRef<'_>, &dyn QueryParameter);
}

/// Bounds to some type T in order to make it callable over some fn parameter T
///
/// Represents the ability of a struct to be considered as candidate to perform
/// actions over it as it holds the 'parent' side of a foreign key relation.
///
/// Usually, it's used on the Canyon macros to retrieve the column that
/// this side of the relation it's representing
pub trait ForeignKeyable<T> {
    /// Returns the actual value of the field related to the column passed in
    fn get_fk_column(&self, column: &str) -> Option<&dyn QueryParameter>;
}
