use canyon_core::connection::contracts::DbConnection;
use canyon_core::connection::database_type::DatabaseType;
use canyon_core::mapper::RowMapper;
use canyon_core::query::bounds::Inspectionable;
use canyon_core::query::parameters::QueryParameter;
use canyon_core::query::querybuilder::{
    DeleteQueryBuilder, SelectQueryBuilder, UpdateQueryBuilder,
};
use std::error::Error;
use std::future::Future;

pub trait Insertable {
    // Logically, this looks more like Inserter, and Insertable w'd be the ones with &self
    fn insert_entity<'a, T>(
        entity: &'a T,
    ) -> impl Future<Output = Result<(), Box<(dyn Error + Send + Sync + 'a)>>> + Send
    where
        T: RowMapper + Inspectionable;
    // fn insert_entity_with<'a, I>(
    //     &mut self,
    //     input: I,
    // ) -> impl Future<Output = Result<(), Box<(dyn Error + Send + Sync + 'a)>>> + Send
    // where
    //     I: DbConnection + Send + 'a;
}

/// *CrudOperations* it's the core part of Canyon-SQL.
///
/// Here it's defined and implemented every CRUD operation
/// that the user has available, just by deriving the `CanyonCrud`
/// derive macro when a struct contains the annotation.
///
/// Also, these traits needs that the type R over what it's generified
/// to implement certain types in order to work correctly.
///
/// The most notorious one it's the [`RowMapper`] one, which allows
/// Canyon to directly maps database results into structs.
///
/// See it's definition and docs to see the implementations.
/// Also, you can find the written macro-code that performs the auto-mapping
/// in the *canyon_sql_root::canyon_macros* crates, on the root of this project.
pub trait CrudOperations<R>: Send + Sync
where
    R: RowMapper,
    Vec<R>: FromIterator<<R as RowMapper>::Output>,
{
    fn find_all() -> impl Future<Output = Result<Vec<R>, Box<(dyn Error + Send + Sync)>>> + Send;

    fn find_all_with<'a, I>(
        input: I,
    ) -> impl Future<Output = Result<Vec<R>, Box<(dyn Error + Send + Sync)>>> + Send
    where
        I: DbConnection + Send + 'a;

    fn select_query<'a>() -> Result<SelectQueryBuilder<'a>, Box<(dyn Error + Send + Sync + 'a)>>;

    fn select_query_with<'a>(
        database_type: DatabaseType,
    ) -> Result<SelectQueryBuilder<'a>, Box<(dyn Error + Send + Sync + 'a)>>;

    fn count() -> impl Future<Output = Result<i64, Box<(dyn Error + Send + Sync)>>> + Send;

    fn count_with<'a, I>(
        input: I,
    ) -> impl Future<Output = Result<i64, Box<(dyn Error + Send + Sync + 'a)>>> + Send
    where
        I: DbConnection + Send + 'a;

    fn find_by_pk<'a>(
        value: &'a dyn QueryParameter<'a>,
    ) -> impl Future<Output = Result<Option<R>, Box<(dyn Error + Send + Sync + 'a)>>> + Send;

    fn find_by_pk_with<'a, I>(
        value: &'a dyn QueryParameter<'a>,
        input: I,
    ) -> impl Future<Output = Result<Option<R>, Box<(dyn Error + Send + Sync + 'a)>>> + Send
    where
        I: DbConnection + Send + 'a;

    /// Inserts the current instance into the corresponding database table using the default datasource.
    ///
    /// This asynchronous operation creates a new row in the database based on the data in `self`.
    /// Upon successful insertion, it updates the primary key field (`self.<pk_field>`) with the value
    /// generated by the database.
    ///
    /// # Behavior
    ///
    /// - Requires a mutable reference to `self` (`&mut self`) because the method updates the primary key field.
    /// - Utilizes the default datasource as specified in the configuration.
    /// - Returns a `Result` indicating success or failure of the operation.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - The insertion fails due to database constraints or connectivity issues.
    /// - The default datasource is not properly configured or unavailable.
    ///
    /// # Examples
    ///
    /// ```rust
    /// let mut lec = League {
    ///     id: Default::default(),
    ///     ext_id: 1,
    ///     slug: "LEC".to_string(),
    ///     name: "League Europe Champions".to_string(),
    ///     region: "EU West".to_string(),
    ///     image_url: "https://lec.eu".to_string(),
    /// };
    ///
    /// println!("Before insert: {:?}", lec);
    ///
    /// match lec.insert().await {
    ///     Ok(_) => println!("After insert: {:?}", lec),
    ///     Err(e) => eprintln!("Insert failed: {:?}", e),
    /// }
    /// ```
    ///
    /// # Notes
    ///
    /// Ensure that the default datasource is correctly configured in your application settings.
    /// The primary key field must be set to some column before calling `insert`, otherwise, the
    /// operation will be launched anyway and will insert all the fields, so ensure that your table
    /// your [`Canyon`] annotations matches your database definitions
    fn insert<'a>(
        &'a mut self,
    ) -> impl Future<Output = Result<(), Box<(dyn Error + Send + Sync + 'a)>>> + Send;

    /// # Brief
    ///
    /// This operation is the same as [`self.insert()`](method@self.insert)
    ///
    ///
    /// Inserts the current instance into the specified datasource.
    ///
    /// Similar to [`insert`](Self::insert), but allows specifying the datasource to use for the operation.
    ///
    /// # Parameters
    ///
    /// - `input`: An implementation of [`DbConnection`] representing the target datasource.
    ///
    /// # Behavior
    ///
    /// - Requires a mutable reference to `self` (`&mut self`) because the method updates the primary key field.
    /// - Uses the provided `DbConnection` instead of the default datasource.
    /// - Returns a `Result` indicating success or failure of the operation.
    ///
    /// # Errors
    ///
    /// Returns an error if:
    /// - The insertion fails due to database constraints or connectivity issues.
    /// - The provided datasource is not properly configured or unavailable.
    ///
    /// # Examples
    ///
    /// ```ignore
    /// let mut lec = League {
    ///     id: Default::default(),
    ///     ext_id: 1,
    ///     slug: "LEC".to_string(),
    ///     name: "League Europe Champions".to_string(),
    ///     region: "EU West".to_string(),
    ///     image_url: "https://lec.eu".to_string(),
    /// };
    ///
    /// let custom_connection = canyon_sql::core::Canyon()::instance()?
    ///     .get_default_connection()?
    ///     .lock()
    ///     .await;
    ///
    /// match lec.insert_with(custom_connection).await {
    ///     Ok(_) => println!("Insert successful"),
    ///     Err(e) => eprintln!("Insert failed: {:?}", e),
    /// }
    /// ```
    ///
    /// # Notes
    ///
    /// Use this method when you need to insert data into a specific datasource other than the default,
    /// or when you have an actual mock of the [`DbConnection`] implementor and you're interested in
    /// unit testing your procedure.
    fn insert_with<'a, I>(
        &mut self,
        input: I,
    ) -> impl Future<Output = Result<(), Box<(dyn Error + Send + Sync + 'a)>>> + Send
    where
        I: DbConnection + Send + 'a;

    fn insert_entity<'a, T>(
        entity: &'a mut T,
    ) -> impl Future<Output = Result<(), Box<(dyn Error + Send + Sync + 'a)>>>
    where
        T: RowMapper + Inspectionable + Sync + 'a;

    fn insert_entity_with<'a, T, I>(
        entity: &'a mut T,
        input: I,
    ) -> impl Future<Output = Result<(), Box<(dyn Error + Send + Sync + 'a)>>>
    where
        T: RowMapper + Inspectionable + Sync + 'a,
        I: DbConnection + Send + 'a;

    // TODO: the horripilant multi_insert MUST be replaced with a batch insert
    // fn multi_insert<'a, T>(
    //     instances: &'a mut [&'a mut T],
    // ) -> impl Future<Output = Result<(), Box<(dyn Error + Send + Sync + 'a)>>> + Send;
    //
    // fn multi_insert_with<'a, T, I>(
    //     instances: &'a mut [&'a mut T],
    //     input: I,
    // ) -> impl Future<Output = Result<(), Box<(dyn Error + Send + Sync + 'a)>>> + Send
    // where
    //     I: DbConnection + Send + 'a;

    fn update(&self) -> impl Future<Output = Result<u64, Box<(dyn Error + Send + Sync)>>> + Send;

    fn update_with<'a, I>(
        &self,
        input: I,
    ) -> impl Future<Output = Result<u64, Box<(dyn Error + Send + Sync + 'a)>>> + Send
    where
        I: DbConnection + Send + 'a;

    fn update_query<'a>() -> Result<UpdateQueryBuilder<'a>, Box<(dyn Error + Send + Sync + 'a)>>;

    fn update_query_with<'a>(
        database_type: DatabaseType,
    ) -> Result<UpdateQueryBuilder<'a>, Box<(dyn Error + Send + Sync + 'a)>>;

    fn delete(&self) -> impl Future<Output = Result<(), Box<(dyn Error + Send + Sync)>>> + Send;

    fn delete_with<'a, I>(
        &self,
        input: I,
    ) -> impl Future<Output = Result<(), Box<(dyn Error + Send + Sync + 'a)>>> + Send
    where
        I: DbConnection + Send + 'a;

    fn delete_query<'a>() -> Result<DeleteQueryBuilder<'a>, Box<(dyn Error + Send + Sync + 'a)>>;

    fn delete_query_with<'a>(
        database_type: DatabaseType,
    ) -> Result<DeleteQueryBuilder<'a>, Box<(dyn Error + Send + Sync + 'a)>>;
}
