[package]
name = "canyon_migrations"
version.workspace = true
edition.workspace = true
authors.workspace = true
documentation.workspace = true
homepage.workspace = true
readme.workspace = true
license.workspace = true
description.workspace = true

[dependencies]
canyon_core = { workspace = true }
canyon_crud = { workspace = true }
canyon_entities = { workspace = true }

tokio-postgres = { workspace = true, optional = true }
tiberius = { workspace = true, optional = true }
mysql_async = { workspace = true, optional = true }
mysql_common = { workspace = true, optional = true }

regex = { workspace = true }
partialdebug = { workspace = true }
walkdir = { workspace = true }

[features]
postgres = ["tokio-postgres", "canyon_core/postgres", "canyon_crud/postgres"]
mssql = ["tiberius", "canyon_core/mssql", "canyon_crud/mssql"]
mysql = ["mysql_async", "mysql_common", "canyon_core/mysql", "canyon_crud/mysql"]

